export const en = {
  bookmarksBar: "Bookmarks bar",
  otherBookmarks: "Other bookmarks",
  mobileBookmarks: "Mobile bookmarks",
  home: "Home",
  work: "Work",
  inspiration: "Inspiration",
  daily: "Daily",
  social: "Social",
  shopping: "Shopping",
  tools: "Tools",
  news: "News",
  travel: "Travel",
  development: "Development",
  google: "Google",
  reading: "Reading",
  somewhere: "Somewhere",
  resources: "Resources",
} as const;
